# Generated by Django 5.2.16 on 2026-08-04 16:59

import complaints.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Pothole', 'Pothole'), ('Road Crack', 'Road Crack'), ('Garbage', 'Garbage'), ('Drainage', 'Drainage'), ('Waterlogging', 'Waterlogging'), ('Streetlight', 'Streetlight')], max_length=30)),
                ('image', models.ImageField(upload_to=complaints.utils.complaint_image_path)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=20)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Submitted', max_length=20)),
                ('ai_prediction', models.CharField(blank=True, default='', max_length=100)),
                ('confidence', models.FloatField(default=0)),
                ('severity', models.CharField(blank=True, default='', max_length=20)),
                ('decision_support', models.TextField(blank=True, default='')),
                ('ai_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
